DELETE  http://localhost:4000/api/user/1

###

PUT http://localhost:4000/api/user/1
Content-Type: application/json

{
	"username":"jijijiji",
	"password":"popo",
	"email":"roberto@gmail.com"
}

###

POST http://localhost:4000/api/user/
Content-Type: application/json

{
	"username":"ov",
	"password":"vargas",
	"email":"oscar@gmail.com"
}