---
version: '3.8'
services:
  nodejs:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/Dockerfile.nodejs
      target: base
    image: nodejs-base-${PROJECT_NAME}
    container_name: nodejs-base-${PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DD_DATABASE_USER: ${DATABASE_USER}
      DD_DATABASE_HOST: ${DATABASE_HOST}
      DD_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DD_DATABASE_DIALECT: ${DATABASE_DIALECT}
