---
version: '3.8'
services:
  react:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/Dockerfile.react
      target: base
    image: react-base-${PROJECT_NAME}
    container_name: react-base-${PROJECT_NAME}
    depends_on:
      - nodejs
    ports:
      - target: 3000
        published: ${DD_PORT:-3000}
        protocol: tcp
        mode: host
  nodejs:
    build:
      context: ../
      dockerfile: ./docker/dockerfiles/Dockerfile.nodejs
      target: base
    image: nodejs-base-${PROJECT_NAME}
    container_name: nodejs-base-${PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      DD_DATABASE_USER: ${DATABASE_USER}
      DD_DATABASE_HOST: ${DATABASE_HOST}
      DD_DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DD_DATABASE_DIALECT: ${DATABASE_DIALECT}
    links:
      - mysql
  mysql:
    image: mysql:5.7.38@sha256:16e159331007eccc069822f7b731272043ed572a79a196a05ffa2ea127caaf67
    container_name: mysql-base-${PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      DD_DATABASE_DIALECT: ${DATABASE_DIALECT}
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
