---
version: '3.8'
services:
  nodejs:
    build:
      target: development
    image: nodejs-dev-${PROJECT_NAME}
    container_name: nodejs-dev-${PROJECT_NAME}
    ports:
      - target: 4000
        published: ${DD_PORT:-4000}
        protocol: tcp
        mode: host
    restart: always
    environment:
      DD_DATABASE_NAME: ${DEV_DATABASE_NAME}
    volumes:
      - ../server/sequelize:/myapp/sequelize:z
      - ../server/src:/myapp/src:z
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports:
      - 8081:80
